dependencies {
    // Anvil Lib
    implementation(libs.anvillib)

    // AnvilCraft
    implementation(libs.anvilcraft) { transitive = false }
    interfaceInjectionData(libs.anvilcraft) { transitive = false }

    // JEI
    compileOnly(libs.jeiCommonApi)
    compileOnly(libs.jeiNeoForgeApi)
    runtimeOnly(libs.jeiNeoForge)
}
